syshacienda/bi/urls.py
from django.urls import path, include
from bi.views import analiticaView, superficieView, rendimientoView, cantidadesView, \
                    costoproduccionView, precioventaView, lotescultivadosView, \
                    masproducidosView, valorminimoView, valormaximoView, valorpromedioView, \
                    masproduciraView, proximafechaView

urlpatterns = [
    path('analitica', analiticaView, name="analiticaView"),
    path('superficie', superficieView, name="superficieView"),
    path('rendimiento', rendimientoView, name="rendimientoView"),
    path('cantidades', cantidadesView, name="cantidadesView"),
    path('costoproduccion', costoproduccionView, name="costoproduccionView"),    
    path('precioventa', precioventaView, name="precioventaView"),    
    path('lotescultivados', lotescultivadosView, name="lotescultivadosView"),    
    path('masproducidos', masproducidosView, name="masproducidosView"),    
    path('valorminimo', valorminimoView, name="valorminimoView"),
    path('valormaximo', valormaximoView, name="valormaximoView"),
    path('valorpromedio', valorpromedioView, name="valorpromedioView"),
    path('masproducira', masproduciraView, name="masproduciraView"),
    path('proximafecha', proximafechaView, name="proximafechaView"),
]

syshacienda/rpts/urls.py
from django.urls import path, include
from rpts.views import iProveedoresView, iClientesView, \
                        iComprasView, iComprasView_, \
                        oProduccionView, oProductosMasVendidosView, \
                        oVentasPorCultivoView, oGananciasView, \
                        impComprasView, impGananciasView, impProduccionView, \
                        impProductosMasVendidosView, impVentasPorCultivoView
                        
from rpts.reportes import imprimirClientes, imprimirProveedores

urlpatterns = [
    #Reportes
    path('informe/proveedores', iProveedoresView.as_view(template_name='rpts/iProveedores.html'), name='iproveedores'),
    path('informe/clientes', iClientesView.as_view(template_name='rpts/iClientes.html'), name='iclientes'),
    path('informe/compras', iComprasView, name='icompras'),
    path('informe/produccion', oProduccionView, name='iproduccion'),
    path('informe/productosmasvendidos', oProductosMasVendidosView, name='iproductosmasvendidos'),
    path('informe/ventasporcultivo', oVentasPorCultivoView, name='iventasporcultivo'),
    path('informe/ganancias', oGananciasView, name='iganancias'),

    #Impresión
    path('informe/imprimir/clientes', imprimirClientes, name="imprimirclientes"),
    path('informe/imprimir/proveedores', imprimirProveedores, name="imprimirproveedores"),
    path('informe/imprimir/compras/<int:f1>', impComprasView , name="imprimircompras"),
    path('informe/imprimir/ganancias/<int:f1>', impGananciasView , name="imprimirganancias"),
    path('informe/imprimir/produccion/<int:f1>', impProduccionView , name="imprimirproduccion"),
    path('informe/imprimir/productos/<int:f1>', impProductosMasVendidosView , name="imprimirproductos"),
    path('informe/imprimir/ventas/<int:f1>', impVentasPorCultivoView , name="imprimirventas"),
    
]

syshacienda/syshacienda/urls.py
from django.contrib import admin
from django.urls import path, include
from baseapp import urls
from mnt import urls
from vent import urls
from api import urls
from bi import urls

urlpatterns = [
    path('', include(('baseapp.urls','baseapp'), namespace="baseapp")),
    path('mnt/', include(('mnt.urls','mnt'), namespace="mnt")),
    path('vent/', include(('vent.urls','vent'), namespace="vent")),
    path('api/', include(('api.urls','api'), namespace="api")),
    path('rpts/', include(('rpts.urls','rpts'), namespace="rpts")),
    path('bi/', include(('bi.urls','bi'), namespace="bi")),

    path('admin',admin.site.urls),

]

admin.site.site_header = 'Panel de control de Administración de Hacienda'
admin.site.index_title = 'ADMINISTRACIÓN DEL SISTEMA'
#admin.site.site_title = 'SysAdmin'
 # 

syshacienda/rpts/models.py
from django.db import models

#Para los signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum


from django.db import models
from vent.models import Venta, DetalleVenta
from mnt.models import Cliente, Cultivo, Produccion, Empleado, Asignacion, Proveedor
# Create your models here.

syshacienda/rpts/views.py
from django.db import models
from django.shortcuts import render,redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.messages.views import SuccessMessageMixin
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.db.models import Sum, F, DateTimeField, Count, FloatField, IntegerField, Prefetch, Case, When
from datetime import datetime, timezone
from django.db.models.functions import TruncMonth, TruncYear, ExtractMinute, ExtractMonth, ExtractYear, Cast, Coalesce
from django.db.models.query import Q
import json
from django.http import HttpResponse
from datetime import datetime
from django.contrib import messages
from django.contrib.auth import authenticate

from mnt.views import ClienteView, CultivoView, ProduccionView, \
                            HaciendaView, EmpleadoNew, AsignacionView, \
                            ProveedorNew, RegistroInsumoNew
from mnt.models import Cliente, Cultivo, Produccion, DescripcionLote, \
                        Hacienda, Empleado, Asignacion, \
                        Proveedor, RegistroInsumo, Insumo, \
                        Parametro
from vent.views import ventasView, VentaView
from vent.models import Venta, DetalleVenta
# Create your views here.


class iProveedoresView(LoginRequiredMixin, generic.ListView):
    model = Proveedor
    template_name="rpts/iProveedores.html"
    context_object_name = "obj"
    login_url = "baseapp:login"

class iClientesView(LoginRequiredMixin, generic.ListView):
    model = Cliente
    template_name="rpts/iClientes.html"
    context_object_name = "obj"
    login_url = "baseapp:login"

class iComprasView_(LoginRequiredMixin, generic.ListView):
    model = RegistroInsumo
    template_name="rpt/iCompras.html"
    context_object_name = "obj"
    login_url = "baseapp:login"
# Reportes
@login_required(login_url='/login/')
def iComprasView(request):
    template_name="rpts/iCompras.html"
    anioactual = datetime.now().year
    dFecha = datetime.now().year

    if request.method == 'POST':
        dFecha = int(request.POST.get("id_anios"))


    #if request.method == 'GET':
    #    if f1 is not None:
    #        dFecha = f1

    #if request.method == 'POST':
    #    f1 = int(request.POST.get("id_anios"))
    #    if f1 is not None:
    #        dFecha = f1

    anios = int(Parametro.objects.filter(nombreParametro="ANIOS") \
                            .values_list('valorParametro', flat=True) \
                            .annotate(valor_parametro=Cast('valorParametro', IntegerField())) \
                            .get())

    ianio = dFecha
    ianio_anterior = ianio-1

    obj = RegistroInsumo.objects \
                        .filter(fechaCompra__year=ianio) \
                        .annotate(anio=F('fechaCompra__year'),
                                    month=F('fechaCompra__month'),
                                    insumo_name=F('insumo__nombre')) \
                        .values('anio','month', 'insumo_name') \
                        .annotate(total_compras=Sum('precio')) \
                        .order_by('anio','month')

    oanios = [i for i in range(anioactual,(anioactual - anios),-1)]

    dato1 = {'01': 0, '02': 0, '03': 0, '04': 0,
             '05': 0, '06': 0, '07': 0, '08': 0,
             '09': 0, '10': 0, '11': 0, '12': 0}
    dato2 = {'01': 0, '02': 0, '03': 0, '04': 0,
             '05': 0, '06': 0, '07': 0, '08': 0,
             '09': 0, '10': 0, '11': 0, '12': 0}

    datoLineal = RegistroInsumo.objects \
                                .filter(fechaCompra__year=ianio) \
                                .annotate(month=ExtractMonth('fechaCompra'), year=ExtractYear('fechaCompra')) \
                                .values('month', 'year') \
                                .annotate(total=Cast(Sum('precio'), IntegerField()))  \
                                .annotate(total_int=Cast(Sum('precio'), IntegerField())) \
                                .order_by('month')

    datoComprativo = RegistroInsumo.objects \
                                .filter(fechaCompra__year=ianio_anterior) \
                                .annotate(month=ExtractMonth('fechaCompra'), year=ExtractYear('fechaCompra')) \
                                .values('month', 'year') \
                                .annotate(total=Cast(Sum('precio'), IntegerField())) \
                                .order_by('month')

    for item in datoLineal:
        if item.get('month') == 1:
            dato1['01'] = item.get('total')
        if item.get('month') == 2:
            dato1['02'] = item.get('total')
        if item.get('month') == 3:
            dato1['03'] = item.get('total')
        if item.get('month') == 4:
            dato1['04'] = item.get('total')
        if item.get('month') == 5:
            dato1['05'] = item.get('total')
        if item.get('month') == 6:
            dato1['06'] = item.get('total')
        if item.get('month') == 7:
            dato1['07'] = item.get('total')
        if item.get('month') == 8:
            dato1['08'] = item.get('total')
        if item.get('month') == 9:
            dato1['09'] = item.get('total')
        if item.get('month') == 10:
            dato1['10'] = item.get('total')
        if item.get('month') == 11:
            dato1['11'] = item.get('total')
        if item.get('month') == 12:
            dato1['12'] = item.get('total')

    for item in datoComprativo:
        if item.get('month') == 1:
            dato2['01'] = item.get('total')
        if item.get('month') == 2:
            dato2['02'] = item.get('total')
        if item.get('month') == 3:
            dato2['03'] = item.get('total')
        if item.get('month') == 4:
            dato2['04'] = item.get('total')
        if item.get('month') == 5:
            dato2['05'] = item.get('total')
        if item.get('month') == 6:
            dato2['06'] = item.get('total')
        if item.get('month') == 7:
            dato2['07'] = item.get('total')
        if item.get('month') == 8:
            dato2['08'] = item.get('total')
        if item.get('month') == 9:
            dato2['09'] = item.get('total')
        if item.get('month') == 10:
            dato2['10'] = item.get('total')
        if item.get('month') == 11:
            dato2['11'] = item.get('total')
        if item.get('month') == 12:
            dato2['12'] = item.get('total')

    salida1 = [dato1[key] for key in dato1]
    salida2 = [dato2[key] for key in dato2]

    context = {'obj': obj, 'datoLineal':  salida1,
            'datoComparativo': salida2, 'dFecha': dFecha,
            'ianio': ianio, 'ianio_anterior':ianio_anterior,
            'anios': oanios}

    return render(request,
                    template_name,
                    context)

@login_required(login_url='/login/')
def oProduccionView(request):
    template_name="rpts/oProduccionPorHALote.html"
    anioactual = datetime.now().year
    dFecha = datetime.now().year

    if request.method == 'POST':
        dFecha = int(request.POST.get("id_anios"))

    anios = int(Parametro.objects.filter(nombreParametro="ANIOS") \
                            .values_list('valorParametro', flat=True) \
                            .annotate(valor_parametro=Cast('valorParametro', IntegerField())) \
                            .get())

    ianio = dFecha
    ianio_anterior = ianio-1

    obj =  Produccion.objects.filter(fecha__year=ianio) \
                            .annotate(mes=ExtractMonth('fecha'), anio=ExtractYear('fecha')) \
                            .values('mes', 'anio', 'cultivo__nombre') \
                            .annotate(total_cosecha=Cast(Sum('cantidadCosecha') / Count('cantidadVentaCosecha'),IntegerField()) , total_venta_cosecha =Sum('cantidadVentaCosecha'),total_descripcionlote_area =Cast(Sum('descripcionlote__area'),IntegerField())) \
                            .order_by('anio', 'mes')

    oanios = [i for i in range(anioactual,(anioactual - anios),-1)]

    datoLineal = Produccion.objects.filter(fecha__year=ianio) \
                            .values('cultivo__nombre') \
                            .annotate(total_cosecha=Cast(Sum('cantidadCosecha'),IntegerField()),\
                                        total_venta_cosecha=Cast(Sum('cantidadVentaCosecha'),IntegerField())) \
                            .order_by('cultivo__nombre')

    datoComprativo = Produccion.objects.filter(fecha__year=ianio) \
                            .values('cultivo__nombre') \
                            .annotate(total_cosecha=Cast(Sum('cantidadCosecha'),IntegerField())) \
                            .order_by('cultivo__nombre')


    context = {'obj': obj, 'datoLineal':  datoLineal,
            'datoComparativo': datoComprativo, 'dFecha': dFecha,
            'ianio': ianio, 'ianio_anterior':ianio_anterior,
            'anios': oanios}

    return render(request,
                    template_name,
                    context)

@login_required(login_url='/login/')
def oProductosMasVendidosView(request):
    template_name="rpts/oProductosMasVendidos.html"
    anioactual = datetime.now().year
    dFecha = datetime.now().year

    if request.method == 'POST':
        dFecha = int(request.POST.get("id_anios"))

    anios = int(Parametro.objects.filter(nombreParametro="ANIOS") \
                            .values_list('valorParametro', flat=True) \
                            .annotate(valor_parametro=Cast('valorParametro', IntegerField())) \
                            .get())

    ianio = dFecha
    ianio_anterior = ianio-1
    ventas = Venta.objects.filter(fechaVenta__year=ianio)
    obj =  ventas.values('fechaVenta__year', 'detalleventa__cultivo__nombre') \
                .annotate(cantidad=Count('detalleventa__cultivo'), det_total=Sum('detalleventa__total'), det_cantidad=Sum('detalleventa__cantidad')) \
                .order_by('-cantidad')

syshacienda/rpts/templates/rpts/base_list.html
{% extends 'base/home.html' %}
{% load static %}

{% block csstables %}

  <!-- Custom fonts for this template -->
  <link href="{% static 'assets/vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'assets/vendor/css/sb-admin-2.min.css'%}" rel="stylesheet">

  
   <!-- Custom styles for this page -->
   <link href="{% static 'assets/vendor/datatables/dataTables.bootstrap4.min.css'%}" rel="stylesheet">
     <!-- jQuery Confirm -->
  <link rel="stylesheet" href="{% static 'assets/vendor/jquery_confirm/jquery-confirm.min.css' %}">

  <!-- XDSoft DateTimePicker -->  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" 
            integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />  

  <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/css/select2.min.css" rel="stylesheet" />

{% endblock csstables %}

{% block page_content %}  

<div class="container-fluid">
      
    <div class="app-card-body p-1 p-lg-1">
    </div>

<!-- Begin Page Content -->
        <div class="container-fluid">
          <!-- DataTales Example -->         
          <div class="card shadow mb-4" ><br/>
                <div class="app-card-body p-1 p-lg-1">
                    <div class="row gx-5 gy-3">
                      <div class="col-12 col-lg-9">
                            {% block mensaje %}
                            {% endblock %}
                      </div>
                      <div class="col-12 col-lg-3">
                            {% block btnnuevo %}
                            {% endblock  %}
                      </div><!--//col-->
                    </div><!--//row-->
                </div>
                {% if not obj %}
                    <div class="card-header py-2">
                      <h2 class="alert alert-info">No hay información para generar reporte</h2>
                    </div>
                {% else %}
                    <div class="card-body">
                        <table class="table table-responsive table-bordered" 
                               id="dataTable" width="100%" cellspacing="0">
                          <thead>
                                {% block header_list %}
                                {% endblock %}
                          </thead>
                          <tfoot>
                                {% block footer_list %}
                                {% endblock %}
                          </tfoot>
                          <tbody>
                                {% block body_list %}
                                {% endblock %}
                          </tbody>
                        </table>
                    </div>
                  </div>
                {% endif %}
        </div>
        <!-- /.container-fluid -->
{% endblock %}
{% block js_tablas %}
	<!-- Page level plugins -->
	<script src="{% static 'assets/vendor/datatables/jquery.dataTables.min.js'%}"></script>
	<script src="{% static 'assets/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

	<!-- Bootstrap core JavaScript-->
	<script src="{% static 'assets/vendor/jquery/jquery.min.js'%}"></script>
	<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

	<!-- Core plugin JavaScript-->
	<script src="{% static 'assets/vendor/jquery-easing/jquery.easing.min.js'%}"></script>

	<!-- Page level custom scripts -->
	<script src="{% static 'assets/vendor/js/demo/datatables-demo.js'%}"></script>
{% endblock js_tablas %}

{% block js_page %}
<script>
  var jq = jQuery.noConflict(true);
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock %}

syshacienda/rpts/templates/rpts/iClientes.html
{% extends 'rpts/baserpts.html' %}

{% block mensaje %}
<h2 class="h3 mb-2 text-success">Informe de Clientes</h2>
{% endblock %}

{% block btnnuevo %}
  <a href="{% url 'rpts:imprimirclientes' %}" 
    class="btn btn-primary btn-icon-split">
    <span class="text">Imprimir</span>
  </a>
{% endblock btnnuevo %}

{% block header_list %}
    <tr>
      <th>id</th>
      <th>Nombre y Apellido</th>
      <th>Identificacion</th>
      <th>Celular</th>
      <th>Email</th>
      <th>Ciudad</th>
    </tr>
 {% endblock %}
 {% block footer_list %}
 {% endblock %}
 {% block body_list %}  
      {% for item in obj %}
            <tr>
              <td>{{ item.id }}</td>
              <td width="240px">{{ item.nombre }} {{ item.apellido }}</td>
              <td width="240px">{{ item.identificacion }}</td>
              <td width="240px">{{ item.celular }}</td>
              <td width="240px">{{ item.email }}</td>
              <td width="240px">{{ item.ciudad }} </td>
            </tr>
    {% endfor %}
{% endblock %} 

{% block js_page %}
<script>
  var jq = jQuery.noConflict(true);
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock %}

syshacienda/rpts/templates/rpts/iCompras.html
{% extends 'rpts/baserpts.html' %}
{% load static %}
<!--<style media="print">
  #imprimir { display: block;}   
</style> -->
<style media="print">
.seccion {
    font-family: Arial, sans-serif;
    font-size: 14px;
    line-height: 1.5;
    padding: 10px;
    background-color: #f2f2f2;
}
</style>
{% block mensaje %}
<h2 class="h3 mb-2 text-success">Informe de Compras</h2>
{% endblock %}
{% block btnnuevo %}
{% endblock %}
{% block fechas %}
      <div class="imprimir row">
          <div class="col-lg-1">Año</div>
          <div class="col-md-2">
              <select name="id_anios" id="id_anios" class="form-control">
                  {% for i  in anios %} 
                      <option value="{{i}}">{{i}} </option>
                  {% endfor %}
              </select>
          </div>

          <div class="col-md-2">
            <button type="submit" class="btn btn-info" id="btnConsultar" title="Buscar"> 
                <i class="far fa-chart-bar"></i> 
            </button>
          </div>
          <div class="col-md-2">
            <a href="{% url 'rpts:imprimircompras' ianio  %}" 
                  class="btn btn-primary btn-icon-split">
                <span class="text">Imprimir</span>
            </a>
          </div>
            <!--<input type="button" value="Imprimir" onclick="window.print()"> -->
      </div>
      <br /> <br />
<h2 class="h3 mb-2 text-bg-dark ">Fecha reporte : {{ ianio }}</h2>
<br />

<div class="row g-4 mb-4">
    <div class="col-12 col-lg-6">
    <div class="app-card app-card-chart h-100 shadow-sm">
        <div class="app-card-header p-3 border-0">
          <h4 class="app-card-title">Compras mensuales</h4>
        </div><!--//app-card-header-->
        <div class="app-card-body p-4">					   
          <div class="chart-container">
                  <canvas id="graficoLinea" ></canvas>
          </div>
        </div><!--//app-card-body-->
      </div><!--//app-card-->
    </div><!--//col-->
      <div class="col-12 col-lg-6">		        
      <div class="app-card app-card-chart h-100 shadow-sm">
        <div class="app-card-header p-3 border-0">
          <h4 class="app-card-title">Comparativo anual</h4>
        </div><!--//app-card-header-->
        <div class="app-card-body p-4">					   
          <div class="chart-container">
                  <canvas id="graficoBarra" ></canvas>
          </div>
        </div><!--//app-card-body-->
      </div><!--//app-card-->
      </div><!--//col-->
</div>
{% endblock fechas %}
{% block header_list %}
  <tr>
  <th>Año</th>
  <th>Mes Compra</th>
  <th>Insumo</th>
  <th>Total</th>
  </tr>
{% endblock %}

{% block footer_list %}
{% endblock footer_list %}

{% block body_list %}
  {% for item in obj %}
    <tr>
      <td width="240px">{{ item.anio }}</td>
      <td width="240px">{{ item.month }}</td>
      <td width="240px">{{ item.insumo_name  }}</td>
      <td width="240px">{{ item.total_compras }}</td>
    </tr>
  {% endfor %}
{% endblock %}



{% block js_graficos %}
	<script>
   $(function () {    
    //console.log( {{ datoComprativo }});
    //console.log({{ datoLineal }} );
        window.chartColors = {
          green: '#75c181', // rgba(117,193,129, 1)
          blue: '#5b99ea', // rgba(91,153,234, 1)
          gray: '#a9b5c9',
          text: '#252930',
          border: '#e7e9ed'
        };

        var bkprimario = "rgba(117,193,129,0.8)";
        var bksecundario = "rgba(91,153,234,0.8)";
        var ctx = document.getElementById('graficoBarra').getContext('2d');
        var chart = new Chart(ctx, {
          type: 'bar',
          data: {
            labels: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            datasets: [{
              label: {{ ianio }},
              backgroundColor: bkprimario,
              borderColor: 'gray',
              data: [ {% for data in datoLineal %} {{ data }}, {% endfor %} ],
            },{
              label: {{ ianio_anterior }},
              backgroundColor: bksecundario,
              borderColor: 'yellow',
              data: [{% for data in datoComparativo %} {{ data }},  {% endfor %} ],
            }		
            ]},
            options: {
              responsive: true,
              legend: {
                position: 'bottom',
                align: 'end',
              },

              tooltips: {
                mode: 'index',
                intersect: false,
                titleMarginBottom: 10,
                bodySpacing: 10,
                xPadding: 16,
                yPadding: 16,
                borderColor: window.chartColors.border,
                borderWidth: 1,
                backgroundColor: '#fff',
                bodyFontColor: window.chartColors.text,
                titleFontColor: window.chartColors.text,
                callbacks: {
                          label: function(tooltipItem, data) {	                 
                            return tooltipItem.value + '';   
                          }
                      },
              },
              scales: {
                xAxes: [{
                  display: true,
                  gridLines: {
                    drawBorder: false,
                    color: window.chartColors.border,
                  },
                }],
                yAxes: [{
                  display: true,
                  gridLines: {
                    drawBorder: false,
                    color: window.chartColors.borders,
                  },
                  ticks: {
                          beginAtZero: true,
                          userCallback: function(value, index, values) {
                              return value + '';  
                          }
                      },
                }]
              }
              
            }
        });
        var ctx1 = document.getElementById('graficoLinea').getContext('2d');
        var chart = new Chart(ctx1, {
          type: 'line',
          data: {
            labels: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            datasets: [{
              label: {{ ianio }},
              backgroundColor: bkprimario,
              borderColor: 'gray',
              data: [{% for data in datoLineal %} {{ data }}, {% endfor %}  ],
            }		
            ]},
            options: {
              responsive: true,		
              
              legend: {
                display: true,
                position: 'bottom',
                align: 'end',
              },

              tooltips: {
                mode: 'index',
                intersect: false,
                titleMarginBottom: 10,
                bodySpacing: 10,
                xPadding: 16,
                yPadding: 16,
                borderColor: window.chartColors.border,
                borderWidth: 1,
                backgroundColor: '#fff',
                bodyFontColor: window.chartColors.text,
                titleFontColor: window.chartColors.text,
                      callbacks: {
                          label: function(tooltipItem, data) {	                 
                            return tooltipItem.value + '';   
                          }
                      },
                      

              },
              hover: {
                mode: 'nearest',
                intersect: true
              },
              scales: {
                xAxes: [{
                  display: true,
                  gridLines: {
                    drawBorder: false,
                    color: window.chartColors.border,
                  },
                  scaleLabel: {
                    display: false,
                  
                  }
                }],
                yAxes: [{
                  display: true,
                  gridLines: {
                    drawBorder: false,
                    color: window.chartColors.border,
                  },
                  scaleLabel: {
                    display: false,
                  },
                  ticks: {
                          beginAtZero: true,
                          userCallback: function(value, index, values) {
                              return value.toLocaleString() + '';  
                          }
                      },
                }]
              }
            }
        });
        
     $("#id_anios").val("{{ ianio }}");
   });
	</script>
{% endblock js_graficos%}
<script>
  // Generate charts on load
  window.addEventListener('load', function(){
    
    var lineChart = document.getElementById('graficoLinea').getContext('2d');
    window.myLine = new Chart(lineChart, lineChartConfig);
    
    var barChart = document.getElementById('graficoBarra').getContext('2d');
    window.myBar = new Chart(barChart, barChartConfig);    

  });	
</script>

{% block js_page %}
<script>
  var jq = jQuery.noConflict(true);
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
<!-- Charts JS -->
<script src="{% static 'assets/js/chart.js'%}"></script>
<script src="{% static 'assets/js/chart.min.js'%}"></script>  
<!--<script src="{% static 'assets/js/index-charts.js'%}"></script> --> 
{% endblock %}