syshacienda/bi/urls.py
from django.urls import path, include
from bi.views import analiticaView, superficieView, rendimientoView, cantidadesView, \
                    costoproduccionView, precioventaView, lotescultivadosView, \
                    masproducidosView, valorminimoView, valormaximoView, valorpromedioView, \
                    masproduciraView, proximafechaView

urlpatterns = [
    path('analitica', analiticaView, name="analiticaView"),
    path('superficie', superficieView, name="superficieView"),
    path('rendimiento', rendimientoView, name="rendimientoView"),
    path('cantidades', cantidadesView, name="cantidadesView"),
    path('costoproduccion', costoproduccionView, name="costoproduccionView"),    
    path('precioventa', precioventaView, name="precioventaView"),    
    path('lotescultivados', lotescultivadosView, name="lotescultivadosView"),    
    path('masproducidos', masproducidosView, name="masproducidosView"),    
    path('valorminimo', valorminimoView, name="valorminimoView"),
    path('valormaximo', valormaximoView, name="valormaximoView"),
    path('valorpromedio', valorpromedioView, name="valorpromedioView"),
    path('masproducira', masproduciraView, name="masproduciraView"),
    path('proximafecha', proximafechaView, name="proximafechaView"),
]

syshacienda/mnt/urls.py
from django.urls import path, include
from mnt.views import CultivoView, CultivoNew,CultivoEdit, \
                    InsumoView, InsumoNew, InsumoEdit, \
                    HaciendaView, HaciendaNew, HaciendaEdit, \
                    EmpleadoView, EmpleadoNew, EmpleadoEdit, \
                    ProveedorView, ProveedorNew, ProveedorEdit, \
                    ClienteView, ClienteNew, ClienteEdit, \
                    ActividadView, ActividadNew, ActividadEdit, \
                    AsignacionView, AsignacionNew, AsignacionEdit, \
                    AsignacionMaterialView, AsignacionMaterialNew, AsignacionMaterialEdit, \
                    CosechaView, CosechaNew, CosechaEdit, \
                    RegistroEmpleadoView, RegistroEmpleadoNew, RegistroEmpleadoEdit, \
                    ProduccionView, ProduccionNew, ProduccionEdit, \
                    DescripcionLoteView, DescripcionLoteNew, DescripcionLoteEdit, \
                    RegistroInsumoView, RegistroInsumoNew, RegistroInsumoEdit, \
                    ParametroView, ParametroNew, ParametroEdit

urlpatterns = [
    #Cultivos
    path('Cultivos/', CultivoView.as_view(template_name='mnt/cultivo_list.html'), name='cultivo_list'),
    path('Cultivo/new', CultivoNew.as_view(template_name='mnt/cultivo_form.html'), name='cultivo_new'),
    path('Cultivo/edit/<int:pk>', CultivoEdit.as_view(template_name='mnt/cultivo_form.html'), name='cultivo_edit'),
    #Insumos
    path('Insumos/', InsumoView.as_view(template_name='mnt/insumo_list.html'), name='insumo_list'),
    path('Insumo/new', InsumoNew.as_view(template_name='mnt/insumo_form.html'), name='insumo_new'),
    path('Insumo/edit/<int:pk>', InsumoEdit.as_view(template_name='mnt/insumo_form.html'), name='insumo_edit'),

    #Hacienda
    path('Haciendas/', HaciendaView.as_view(template_name='mnt/hacienda_list.html'), name='hacienda_list'),
    path('Hacienda/new', HaciendaNew.as_view(template_name='mnt/hacienda_form.html'), name='hacienda_new'),
    path('Hacienda/edit/<int:pk>', HaciendaEdit.as_view(template_name='mnt/hacienda_form.html'), name='hacienda_edit'),

    #Empleado
    path('Empleados/', EmpleadoView.as_view(template_name='mnt/empleado_list.html'), name='empleado_list'),
    path('Empleado/new', EmpleadoNew.as_view(template_name='mnt/empleado_form.html'), name='empleado_new'),
    path('Empleado/edit/<int:pk>', EmpleadoEdit.as_view(template_name='mnt/empleado_form.html'), name='empleado_edit'),

    #Proveedor
    path('Proveedores/', ProveedorView.as_view(template_name='mnt/proveedor_list.html'), name='proveedor_list'),
    path('Proveedor/new', ProveedorNew.as_view(template_name='mnt/proveedor_form.html'), name='proveedor_new'),
    path('Proveedor/edit/<int:pk>', ProveedorEdit.as_view(template_name='mnt/proveedor_form.html'), name='proveedor_edit'),

    #Cliente
    path('Clientes/', ClienteView.as_view(template_name='mnt/cliente_list.html'), name='cliente_list'),
    path('Cliente/new', ClienteNew.as_view(template_name='mnt/cliente_form.html'), name='cliente_new'),
    path('Cliente/edit/<int:pk>', ClienteEdit.as_view(template_name='mnt/cliente_form.html'), name='cliente_edit'),

    #Actividad
    path('Actividades/', ActividadView.as_view(template_name='mnt/actividad_list.html'), name='actividad_list'),
    path('Actividad/new', ActividadNew.as_view(template_name='mnt/actividad_form.html'), name='actividad_new'),
    path('Actividad/edit/<int:pk>', ActividadEdit.as_view(template_name='mnt/actividad_form.html'), name='actividad_edit'),
	#path('Actividad/del/<int:pk>', ActividadDel.as_view(template_name='mnt/actividad_form.html'), name='actividad_del'),

    #Asignacion
    path('Asignaciones/', AsignacionView.as_view(template_name='mnt/asignacion_list.html'), name='asignacion_list'),
    path('Asignacion/new', AsignacionNew.as_view(template_name='mnt/asignacion_form.html'), name='asignacion_new'),
    path('Asignacion/edit/<int:pk>', AsignacionEdit.as_view(template_name='mnt/asignacion_form.html'), name='asignacion_edit'),

    #AsignacionMaterial
    path('AsignacionMateriales/', AsignacionMaterialView.as_view(template_name='mnt/asignacionmaterial_list.html'), name='asignacionmaterial_list'),
    path('AsignacionMaterial/new', AsignacionMaterialNew.as_view(template_name='mnt/asignacionmaterial_form.html'), name='asignacionmaterial_new'),
    path('AsignacionMaterial/edit/<int:pk>', AsignacionMaterialEdit.as_view(template_name='mnt/asignacionmaterial_form.html'), name='asignacionmaterial_edit'),

    #Cosecha
    path('Cosechas/', CosechaView.as_view(template_name='mnt/cosecha_list.html'), name='cosecha_list'),
    path('Cosecha/new', CosechaNew.as_view(template_name='mnt/cosecha_form.html'), name='cosecha_new'),
    path('Cosecha/edit/<int:pk>', CosechaEdit.as_view(template_name='mnt/cosecha_form.html'), name='cosecha_edit'),

    #RegistroEmpleado
    path('RegistroEmpleados/', RegistroEmpleadoView.as_view(template_name='mnt/registroempleado_list.html'), name='registroempleado_list'),
    path('RegistroEmpleado/new', RegistroEmpleadoNew.as_view(template_name='mnt/registroempleado_form.html'), name='registroempleado_new'),
    path('RegistroEmpleado/edit/<int:pk>', RegistroEmpleadoEdit.as_view(template_name='mnt/registroempleado_form.html'), name='registroempleado_edit'),

    #Produccion
    path('Produccion/', ProduccionView.as_view(template_name='mnt/produccion_list.html'), name='produccion_list'),
    path('Produccion/new', ProduccionNew.as_view(template_name='mnt/produccion_form.html'), name='produccion_new'),
    path('Produccion/edit/<int:pk>', ProduccionEdit.as_view(template_name='mnt/produccion_form.html'), name='produccion_edit'),

    #DescripcionLote
    path('DescripcionLotes/', DescripcionLoteView.as_view(template_name='mnt/descripcionlote_list.html'), name='descripcionlote_list'),
    path('DescripcionLote/new', DescripcionLoteNew.as_view(template_name='mnt/descripcionlote_form.html'), name='descripcionlote_new'),
    path('DescripcionLote/edit/<int:pk>', DescripcionLoteEdit.as_view(template_name='mnt/descripcionlote_form.html'), name='descripcionlote_edit'),

    #RegistroInsumo
    path('RegistroInsumos/', RegistroInsumoView.as_view(template_name='mnt/registroinsumo_list.html'), name='registroinsumo_list'),
    path('RegistroInsumo/new', RegistroInsumoNew.as_view(template_name='mnt/registroinsumo_form.html'), name='registroinsumo_new'),
    path('RegistroInsumo/edit/<int:pk>', RegistroInsumoEdit.as_view(template_name='mnt/registroinsumo_form.html'), name='registroinsumo_edit'),

    #Parámetro
    path('Parametros/', ParametroView.as_view(template_name='mnt/parametro_list.html'), name='parametro_list'),
    path('Parametro/new', ParametroNew.as_view(template_name='mnt/parametro_form.html'), name='parametro_new'),
    path('Parametro/edit/<int:pk>', ParametroEdit.as_view(template_name='mnt/parametro_form.html'), name='parametro_edit'),

]

syshacienda/syshacienda/urls.py
from django.contrib import admin
from django.urls import path, include
from baseapp import urls
from mnt import urls
from vent import urls
from api import urls
from bi import urls

urlpatterns = [
    path('', include(('baseapp.urls','baseapp'), namespace="baseapp")),
    path('mnt/', include(('mnt.urls','mnt'), namespace="mnt")),
    path('vent/', include(('vent.urls','vent'), namespace="vent")),
    path('api/', include(('api.urls','api'), namespace="api")),
    path('rpts/', include(('rpts.urls','rpts'), namespace="rpts")),
    path('bi/', include(('bi.urls','bi'), namespace="bi")),

    path('admin',admin.site.urls),

]

admin.site.site_header = 'Panel de control de Administración de Hacienda'
admin.site.index_title = 'ADMINISTRACIÓN DEL SISTEMA'
#admin.site.site_title = 'SysAdmin'
 # 

syshacienda/baseapp/models.py
from django.db import models
from django.contrib.auth.models import User

class BaseFields(models.Model):
    estado = models.BooleanField(default=True, verbose_name="Estado del registro")
    fechaCreacion = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creacion")
    fechaModificacion = models.DateTimeField(auto_now = True, verbose_name="Fecha de actualizacion", blank=True, null=True)
    usuarioCreacion = models.ForeignKey(User, on_delete = models.DO_NOTHING, verbose_name="Usuario registra")
    usuarioModificacion = models.IntegerField(blank=True, null=True, verbose_name = "Usuario modifica")

    class Meta:
        abstract = True

class ContactFields(models.Model):
    telefono = models.CharField(max_length=20, blank=True, null=True, verbose_name = "Telefono de contacto")
    celular = models.CharField(max_length=10, blank=True, null=True, verbose_name = "Número celular")
    email = models.CharField(max_length=50, blank=True, null=True, verbose_name = "Correo electrónico")
    direccion = models.CharField(max_length=100, verbose_name="Direccion")
    ciudad = models.CharField(max_length=20, blank=True, null=True, verbose_name= "Ciudad")

    class Meta:
        abstract = True

class PersonFields(models.Model):
    nombre = models.CharField(max_length=25, verbose_name="Nombre")
    apellido = models.CharField(max_length=25, verbose_name="Apellido",blank=True, null=True,)
    identificacion = models.CharField(max_length=15, unique=True, verbose_name = "Número de identificación")
    
    class Meta:
        abstract = True

syshacienda/vent/models.py
from django.db import models
#Para los signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum

from baseapp.models import BaseFields
from mnt.models import Cliente, Cosecha, Produccion, Cultivo, Parametro

## Venta ******************************************** ##
# - Venta - #
class Venta(BaseFields):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True)
    fechaVenta = models.DateTimeField(auto_now_add=True)
    subTotal = models.FloatField(blank=True, null=True, default=0)
    totalVenta = models.FloatField(blank=True, null=True, default=0)
    porcIva    = models.IntegerField(blank=True, null=True, default=0)
    totalIva = models.FloatField(blank=True, null=True, default=0)

    def __str__(self):
        return '{}'.format(self.id)
   
    def save (self):
        self.totalVenta = float(self.totalVenta)
        self.porcIva = self.porcIva
        self.subTotal = float(self.subTotal)
        self.totalIva = float(self.totalIva)
        super(Venta,self).save() 

    class Meta:
        verbose_name_plural = "Ventas"
        db_table = 'venta'

# - DetalleVenta - #
class DetalleVenta(BaseFields):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE, null=True)
    cultivo = models.ForeignKey(Cultivo, on_delete=models.CASCADE, null=True)
    produccion = models.ForeignKey(Produccion, on_delete=models.CASCADE, null=True)
    cantidad = models.FloatField(blank=True, null=True)
    precio = models.FloatField(blank=True, null=True)  
    total = models.FloatField(blank=True, null=True, default=0)

    def __str__(self):
        return "{}".format(self.cultivo.nombre)

    def save (self):
        self.produccion = self.produccion
        self.cultivo = self.cultivo
        self.cantidad = self.cantidad
        self.precio = self.precio
        self.total = round(float(int(self.cantidad)) * float(self.precio),2)
        super(DetalleVenta, self).save()

    class Meta:
        verbose_name_plural = "DetalleVentas"
        db_table = 'detalle_venta'


@receiver(post_save, sender=DetalleVenta)
def detalle_fac_guardar(sender,instance,**kwargs):
    venta_id = instance.venta.id
    produccion_id = instance.produccion.id    
    venta = Venta.objects.get(pk=venta_id)
    iIva = venta.porcIva
    if venta:
        sub_total = DetalleVenta.objects \
            .filter(venta=venta_id) \
            .aggregate(total=Sum('total')) \
            .get('total',0.00)
        
        totaliva = round((sub_total * (iIva /100)),2)
        totalventa = round((sub_total + totaliva),2)
        venta.totalVenta = totalventa
        venta.subTotal  = round(sub_total,2)
        venta.totalIva = totaliva
        venta.porcIva = iIva
        venta.save()

    prod=Produccion.objects.filter(pk=produccion_id).first()
    if prod:
        cantidad = float(prod.cantidadVentaCosecha) + float(instance.cantidad)
        prod.cantidadVentaCosecha = round(cantidad,2)
        prod.save()

syshacienda/mnt/templates/mnt/cliente_form.html
{% extends 'mnt/base_form.html' %}


{% block mensaje_editar %}
    <h4 class="app-card-title text-secondary text-uppercase mb-1"> 
        Editar Cliente    
    </h4>             
{% endblock mensaje_editar %}

{% block mensaje_nuevo %}                     
    <h4 class="app-card-title text-primary text-uppercase mb-1"> 
        Registro Nuevo Cliente
    </h4>
{% endblock mensaje_nuevo %}      
{% block insert_update %}
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="nombre" maxlength="100" 
                        class="form-control" 
                        required id="id_nombre" placeholder="Nombre"
                        pattern="[a-zA-Z \u00f1\u00d1]{2,100}"
                value="{% if obj %} {{obj.nombre}} {% endif %}">
            </div>
        </div>
    </div>   <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="apellido" maxlength="100" 
                class="form-control" 
                required id="id_apellido" placeholder="Apellido"
                pattern="[a-zA-Z \u00f1\u00d1]{2,100}"
                value="{% if obj %} {{ obj.apellido }} {% endif %}">
            </div>
        </div>
    </div>   <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="identificacion" maxlength="13" 
                class="form-control" 
                required id="id_identificacion" 
                pattern="[A-Za-z0-9]{8,13}" title="Permitido Letras y números. Mín: 8 Max: 13"
                placeholder="Identificación"
                value="{% if obj %} {{ obj.identificacion }} {% endif %}">
            </div>
        </div>
    </div>   <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="telefono" maxlength="10" 
                class="form-control" 
                required id="id_telefono" placeholder="Teléfono"
                pattern="[0-9]{7,10}" title="Campo de sólo números. Min: 7 Max: 10"
                value="{% if obj %} {{ obj.telefono }} {% endif %}">
            </div>
        </div>
    </div> <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="celular" maxlength="10"   
                class="form-control" 
                pattern="[0-9]{10}" title="Campo de sólo números. Min: 10"
                required id="id_celular" placeholder="Celular"
                value="{% if obj %} {{ obj.celular }} {% endif %}">
            </div>
        </div>
    </div> <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="email" maxlength="100" 
                class="form-control"  
                required id="id_email" placeholder="Email / Correo electrónico"
                pattern="[a-zA-Z0-9!#$%&'*_+-]([\.]?[a-zA-Z0-9!#$%&'*_+-])+@[a-zA-Z0-9]([^@&%$\/()=?¿!.,:;]|\d)+[a-zA-Z0-9][\.][a-zA-Z]{2,4}([\.][a-zA-Z]{2})?"
                title="Ingresa un mail correcto"
                value="{% if obj %} {{ obj.email }} {% endif %}">
            </div>
        </div>
    </div> <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="direccion" maxlength="100" 
                class="form-control" 
                required id="id_direccion" placeholder="Dirección"
                pattern="[a-zA-Z \u00f1\u00d1]{2,100}"
                value="{% if obj %} {{ obj.direccion }} {% endif %}">
            </div>
        </div>
    </div> <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="ciudad" maxlength="100" 
                class="form-control" 
                required id="id_ciudad" placeholder="Ciudad"
                pattern="[a-zA-Z \u00f1\u00d1]{2,100}"
                value="{% if obj %} {{ obj.ciudad }} {% endif %}">
            </div>
        </div>
    </div>  <br/>
    <div class="row">
        <div class="col-2">
            <label for="id_estado">Estado</label>
        </div>
        <div class="form-group col-10">
            <input type="checkbox" name="estado" 
                class="form-check-input" 
                id="id_estado" width="60px"
                    {% if obj %} 
                        {% if obj.estado %} checked {% else %} null {% endif %} 
                    {% else %} 
                        checked 
                    {% endif %} >
        </div>
    </div>

 {% endblock insert_update %}  

{% block url_list %}
<a href="{% url 'mnt:cliente_list' %}" 
    class="btn btn-danger">
    <span class="fa fa-undo"></span>Cancelar</a>
{% endblock url_list %}

{% block js_page %}
<script type="text/javascript">
    $(function(){
    var campos = $('input');
        
    campos.each(function(index, campo){
        var valor = $(campo).val().trim();
        
        $(campo).val(valor);
    })
    });
</script>
{% endblock %}

syshacienda/mnt/templates/mnt/cultivolist.html
{% extends 'base/home.html' %}

{% block page_content %}
{% endblock %}

{% block js_page %}
{% endblock %}

syshacienda/mnt/templates/mnt/insumo_form.html
{% extends 'mnt/base_form.html' %}


{% block mensaje_editar %}
    <h4 class="app-card-title text-secondary text-uppercase mb-1"> 
        Editar Insumo 
    </h4>
{% endblock mensaje_editar %}                 

{% block mensaje_nuevo %}                     
    <h4 class="app-card-title text-primary text-uppercase mb-1"> 
        Nuevo Insumo / Herramienta
    </h4>
{% endblock mensaje_nuevo %}      
{% block insert_update %}
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="nombre" maxlength="100" 
                        class="form-control" 
                        required id="id_nombre" placeholder="Nombre Insumo"
                        pattern="[a-zA-Z \u00f1\u00d1]{2,100}"
                value="{% if obj %} {{ obj.nombre }} {% endif %}">
            </div>
        </div>
    </div>   <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="tipo" maxlength="100" minlength="8"
                class="form-control" 
                required id="id_tipo" placeholder="Tipo"
                pattern="[a-zA-Z ]{2,100}"
                value="{% if obj %} {{ obj.tipo }} {% endif %}">
            </div>
        </div>
    </div>   <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="uso" maxlength="100" 
                class="form-control" 
                required id="id_uso" placeholder="Uso"
                pattern="[a-zA-Z \u00f1\u00d1]{2,100}"
                value="{% if obj %} {{ obj.uso }} {% endif %}">
            </div>
        </div>
    </div>   <br/>
    <div class="row">
        <div class="col-2">
            <label for="id_precio">Precio: </label>
        </div>
        <div class="col-6">
            <div class="input-group">
                {{ form.precio }}
            </div>
        </div>
    </div> <br/>
    <div class="row">
        <div class="col-2">
            <label for="id_estado">Estado</label>
        </div>
        <div class="form-group col-10">
            <input type="checkbox" name="estado" 
                class="form-check-input" 
                id="id_estado" width="60px"
                    {% if obj %} 
                        {% if obj.estado %} checked {% else %} null {% endif %} 
                    {% else %} 
                        checked 
                    {% endif %} >
        </div>
    </div>
{% endblock insert_update %}
{% block url_list %}
<a href="{% url 'mnt:insumo_list' %}" 
    class="btn btn-danger">
    <span class="fa fa-undo"></span>Cancelar</a>
{% endblock url_list %}

{% block js_page %}
    <script type="text/javascript">
        $(function(){
        var campos = $('input');
            
        campos.each(function(index, campo){
            var valor = $(campo).val().trim();
            
            $(campo).val(valor);
        })
        });
    </script>
{% endblock %}

syshacienda/mnt/templates/mnt/proveedor_form.html
{% extends 'mnt/base_form.html' %}


{% block mensaje_editar %}
    <h4 class="app-card-title text-secondary text-uppercase mb-1"> 
        Editar Proveedor  
    </h4>               
{% endblock mensaje_editar %}

{% block mensaje_nuevo %}                     
    <h4 class="app-card-title text-primary text-uppercase mb-1"> 
        Nuevo Proveedor
    </h4>
{% endblock mensaje_nuevo %}      
{% block insert_update %}
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="nombre" maxlength="100" 
                        class="form-control" 
                        required id="id_nombre" placeholder="Nombre de Proveedor"
                        pattern="[a-zA-Z \u00f1\u00d1]{2,100}"
                value="{% if obj %} {{ obj.nombre }} {% endif %}">
            </div>
        </div>
    </div>   <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="apellido" maxlength="100" 
                class="form-control" 
                required id="id_apellido" placeholder="Razon Social"
                pattern="[a-zA-Z \u00f1\u00d1]{2,100}"
                value="{% if obj %} {{ obj.apellido }} {% endif %}">
            </div>
        </div>
    </div>   <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" 
                    name="identificacion"
                    maxlength="13" required
                    class="form-control" 
                    id="id_identificacion" placeholder="RUC de proveedor"
                    pattern="[0-9]{13}" title="Permitido Letras y números. Mín: 13"
                    value="{% if obj %} {{ obj.identificacion }} {% endif %}"
                    />
            </div>
        </div>
    </div>   <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="telefono" maxlength="10"
                class="form-control" 
                pattern="[0-9]{7,10}" title="Campo de sólo números. Min: 7 Max: 10"
                required id="id_telefono" placeholder="Teléfono"
                value="{% if obj %} {{ obj.telefono }} {% endif %}" >
            </div>
        </div>
    </div> <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="celular" maxlength="10" 
                class="form-control" 
                pattern="[0-9]{10}" title="Campo de sólo números. Min: 10"
                required id="id_celular" placeholder="Celular"
                value="{% if obj %} {{ obj.celular }} {% endif %}">
            </div>
        </div>
    </div> <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="email" maxlength="100" 
                class="form-control"  
                required id="id_email" placeholder="Email / Correo electrónico"
                pattern="[a-zA-Z0-9!#$%&'*_+-]([\.]?[a-zA-Z0-9!#$%&'*_+-])+@[a-zA-Z0-9]([^@&%$\/()=?¿!.,:;]|\d)+[a-zA-Z0-9][\.][a-zA-Z]{2,4}([\.][a-zA-Z]{2})?"
                title="Ingrese un mail correcto"
                value="{% if obj %} {{ obj.email }} {% endif %}">
            </div>
        </div>
    </div> <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="descripcion" maxlength="100" 
                class="form-control" 
                required id="id_descripcion" placeholder="Descripción"
                pattern="[a-zA-Z \u00f1\u00d1]{2,100}"
                value="{% if obj %} {{ obj.descripcion }} {% endif %}">
            </div>
        </div>
    </div> <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="direccion" maxlength="100" 
                class="form-control" 
                required id="id_direccion" placeholder="Dirección"
                pattern="[a-zA-Z \u00f1\u00d1]{2,100}"
                value="{% if obj %} {{ obj.direccion }} {% endif %}">
            </div>
        </div>
    </div> <br/>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="ciudad" maxlength="100" 
                class="form-control" 
                required id="id_ciudad" placeholder="Ciudad"
                pattern="[a-zA-Z \u00f1\u00d1]{2,100}"
                value="{% if obj %} {{ obj.ciudad }} {% endif %}">
            </div>
        </div>
    </div>  <br/>
    <div class="row">
        <div class="col-2">
            <label for="id_estado">Estado</label>
        </div>
        <div class="form-group col-10">
            <input type="checkbox" name="estado" 
                class="form-check-input" 
                id="id_estado" width="60px"
                    {% if obj %} 
                        {% if obj.estado %} checked {% else %} null {% endif %} 
                    {% else %} 
                        checked 
                    {% endif %} >
        </div>
    </div>
 {% endblock insert_update %}  

{% block url_list %}
<a href="{% url 'mnt:proveedor_list' %}" 
    class="btn btn-danger">
    <span class="fa fa-undo"></span>Cancelar</a>
{% endblock url_list %}

{% block js_page %}
    <script type="text/javascript">
        $(function(){
        var campos = $('input');
            
        campos.each(function(index, campo){
            var valor = $(campo).val().trim();
            
            $(campo).val(valor);
        })
        });
    </script>
{% endblock %}