syshacienda/bi/urls.py
from django.urls import path, include
from bi.views import analiticaView, superficieView, rendimientoView, cantidadesView, \
                    costoproduccionView, precioventaView, lotescultivadosView, \
                    masproducidosView, valorminimoView, valormaximoView, valorpromedioView, \
                    masproduciraView, proximafechaView

urlpatterns = [
    path('analitica', analiticaView, name="analiticaView"),
    path('superficie', superficieView, name="superficieView"),
    path('rendimiento', rendimientoView, name="rendimientoView"),
    path('cantidades', cantidadesView, name="cantidadesView"),
    path('costoproduccion', costoproduccionView, name="costoproduccionView"),    
    path('precioventa', precioventaView, name="precioventaView"),    
    path('lotescultivados', lotescultivadosView, name="lotescultivadosView"),    
    path('masproducidos', masproducidosView, name="masproducidosView"),    
    path('valorminimo', valorminimoView, name="valorminimoView"),
    path('valormaximo', valormaximoView, name="valormaximoView"),
    path('valorpromedio', valorpromedioView, name="valorpromedioView"),
    path('masproducira', masproduciraView, name="masproduciraView"),
    path('proximafecha', proximafechaView, name="proximafechaView"),
]

syshacienda/mnt/urls.py
from django.urls import path, include
from mnt.views import CultivoView, CultivoNew,CultivoEdit, \
                    InsumoView, InsumoNew, InsumoEdit, \
                    HaciendaView, HaciendaNew, HaciendaEdit, \
                    EmpleadoView, EmpleadoNew, EmpleadoEdit, \
                    ProveedorView, ProveedorNew, ProveedorEdit, \
                    ClienteView, ClienteNew, ClienteEdit, \
                    ActividadView, ActividadNew, ActividadEdit, \
                    AsignacionView, AsignacionNew, AsignacionEdit, \
                    AsignacionMaterialView, AsignacionMaterialNew, AsignacionMaterialEdit, \
                    CosechaView, CosechaNew, CosechaEdit, \
                    RegistroEmpleadoView, RegistroEmpleadoNew, RegistroEmpleadoEdit, \
                    ProduccionView, ProduccionNew, ProduccionEdit, \
                    DescripcionLoteView, DescripcionLoteNew, DescripcionLoteEdit, \
                    RegistroInsumoView, RegistroInsumoNew, RegistroInsumoEdit, \
                    ParametroView, ParametroNew, ParametroEdit

urlpatterns = [
    #Cultivos
    path('Cultivos/', CultivoView.as_view(template_name='mnt/cultivo_list.html'), name='cultivo_list'),
    path('Cultivo/new', CultivoNew.as_view(template_name='mnt/cultivo_form.html'), name='cultivo_new'),
    path('Cultivo/edit/<int:pk>', CultivoEdit.as_view(template_name='mnt/cultivo_form.html'), name='cultivo_edit'),
    #Insumos
    path('Insumos/', InsumoView.as_view(template_name='mnt/insumo_list.html'), name='insumo_list'),
    path('Insumo/new', InsumoNew.as_view(template_name='mnt/insumo_form.html'), name='insumo_new'),
    path('Insumo/edit/<int:pk>', InsumoEdit.as_view(template_name='mnt/insumo_form.html'), name='insumo_edit'),

    #Hacienda
    path('Haciendas/', HaciendaView.as_view(template_name='mnt/hacienda_list.html'), name='hacienda_list'),
    path('Hacienda/new', HaciendaNew.as_view(template_name='mnt/hacienda_form.html'), name='hacienda_new'),
    path('Hacienda/edit/<int:pk>', HaciendaEdit.as_view(template_name='mnt/hacienda_form.html'), name='hacienda_edit'),

    #Empleado
    path('Empleados/', EmpleadoView.as_view(template_name='mnt/empleado_list.html'), name='empleado_list'),
    path('Empleado/new', EmpleadoNew.as_view(template_name='mnt/empleado_form.html'), name='empleado_new'),
    path('Empleado/edit/<int:pk>', EmpleadoEdit.as_view(template_name='mnt/empleado_form.html'), name='empleado_edit'),

    #Proveedor
    path('Proveedores/', ProveedorView.as_view(template_name='mnt/proveedor_list.html'), name='proveedor_list'),
    path('Proveedor/new', ProveedorNew.as_view(template_name='mnt/proveedor_form.html'), name='proveedor_new'),
    path('Proveedor/edit/<int:pk>', ProveedorEdit.as_view(template_name='mnt/proveedor_form.html'), name='proveedor_edit'),

    #Cliente
    path('Clientes/', ClienteView.as_view(template_name='mnt/cliente_list.html'), name='cliente_list'),
    path('Cliente/new', ClienteNew.as_view(template_name='mnt/cliente_form.html'), name='cliente_new'),
    path('Cliente/edit/<int:pk>', ClienteEdit.as_view(template_name='mnt/cliente_form.html'), name='cliente_edit'),

    #Actividad
    path('Actividades/', ActividadView.as_view(template_name='mnt/actividad_list.html'), name='actividad_list'),
    path('Actividad/new', ActividadNew.as_view(template_name='mnt/actividad_form.html'), name='actividad_new'),
    path('Actividad/edit/<int:pk>', ActividadEdit.as_view(template_name='mnt/actividad_form.html'), name='actividad_edit'),
	#path('Actividad/del/<int:pk>', ActividadDel.as_view(template_name='mnt/actividad_form.html'), name='actividad_del'),

    #Asignacion
    path('Asignaciones/', AsignacionView.as_view(template_name='mnt/asignacion_list.html'), name='asignacion_list'),
    path('Asignacion/new', AsignacionNew.as_view(template_name='mnt/asignacion_form.html'), name='asignacion_new'),
    path('Asignacion/edit/<int:pk>', AsignacionEdit.as_view(template_name='mnt/asignacion_form.html'), name='asignacion_edit'),

    #AsignacionMaterial
    path('AsignacionMateriales/', AsignacionMaterialView.as_view(template_name='mnt/asignacionmaterial_list.html'), name='asignacionmaterial_list'),
    path('AsignacionMaterial/new', AsignacionMaterialNew.as_view(template_name='mnt/asignacionmaterial_form.html'), name='asignacionmaterial_new'),
    path('AsignacionMaterial/edit/<int:pk>', AsignacionMaterialEdit.as_view(template_name='mnt/asignacionmaterial_form.html'), name='asignacionmaterial_edit'),

    #Cosecha
    path('Cosechas/', CosechaView.as_view(template_name='mnt/cosecha_list.html'), name='cosecha_list'),
    path('Cosecha/new', CosechaNew.as_view(template_name='mnt/cosecha_form.html'), name='cosecha_new'),
    path('Cosecha/edit/<int:pk>', CosechaEdit.as_view(template_name='mnt/cosecha_form.html'), name='cosecha_edit'),

    #RegistroEmpleado
    path('RegistroEmpleados/', RegistroEmpleadoView.as_view(template_name='mnt/registroempleado_list.html'), name='registroempleado_list'),
    path('RegistroEmpleado/new', RegistroEmpleadoNew.as_view(template_name='mnt/registroempleado_form.html'), name='registroempleado_new'),
    path('RegistroEmpleado/edit/<int:pk>', RegistroEmpleadoEdit.as_view(template_name='mnt/registroempleado_form.html'), name='registroempleado_edit'),

    #Produccion
    path('Produccion/', ProduccionView.as_view(template_name='mnt/produccion_list.html'), name='produccion_list'),
    path('Produccion/new', ProduccionNew.as_view(template_name='mnt/produccion_form.html'), name='produccion_new'),
    path('Produccion/edit/<int:pk>', ProduccionEdit.as_view(template_name='mnt/produccion_form.html'), name='produccion_edit'),

    #DescripcionLote
    path('DescripcionLotes/', DescripcionLoteView.as_view(template_name='mnt/descripcionlote_list.html'), name='descripcionlote_list'),
    path('DescripcionLote/new', DescripcionLoteNew.as_view(template_name='mnt/descripcionlote_form.html'), name='descripcionlote_new'),
    path('DescripcionLote/edit/<int:pk>', DescripcionLoteEdit.as_view(template_name='mnt/descripcionlote_form.html'), name='descripcionlote_edit'),

    #RegistroInsumo
    path('RegistroInsumos/', RegistroInsumoView.as_view(template_name='mnt/registroinsumo_list.html'), name='registroinsumo_list'),
    path('RegistroInsumo/new', RegistroInsumoNew.as_view(template_name='mnt/registroinsumo_form.html'), name='registroinsumo_new'),
    path('RegistroInsumo/edit/<int:pk>', RegistroInsumoEdit.as_view(template_name='mnt/registroinsumo_form.html'), name='registroinsumo_edit'),

    #Parámetro
    path('Parametros/', ParametroView.as_view(template_name='mnt/parametro_list.html'), name='parametro_list'),
    path('Parametro/new', ParametroNew.as_view(template_name='mnt/parametro_form.html'), name='parametro_new'),
    path('Parametro/edit/<int:pk>', ParametroEdit.as_view(template_name='mnt/parametro_form.html'), name='parametro_edit'),

]

syshacienda/syshacienda/urls.py
from django.contrib import admin
from django.urls import path, include
from baseapp import urls
from mnt import urls
from vent import urls
from api import urls
from bi import urls

urlpatterns = [
    path('', include(('baseapp.urls','baseapp'), namespace="baseapp")),
    path('mnt/', include(('mnt.urls','mnt'), namespace="mnt")),
    path('vent/', include(('vent.urls','vent'), namespace="vent")),
    path('api/', include(('api.urls','api'), namespace="api")),
    path('rpts/', include(('rpts.urls','rpts'), namespace="rpts")),
    path('bi/', include(('bi.urls','bi'), namespace="bi")),

    path('admin',admin.site.urls),

]

admin.site.site_header = 'Panel de control de Administración de Hacienda'
admin.site.index_title = 'ADMINISTRACIÓN DEL SISTEMA'
#admin.site.site_title = 'SysAdmin'
 # 

syshacienda/vent/urls.py
from django.urls import path, include
from vent.views import VentaView, ventasView, ProduccionView, borrar_detalle_factura, ventas_masivasView
from vent.reportes import imprimir_venta_list, imprimir_venta_recibo
urlpatterns = [
    #Ventas
    path('Ventas/', VentaView.as_view(template_name='vent/venta_list.html'), name='venta_list'),
    path('Venta/new', ventasView, name='venta_new'),
    path('Venta/edit/<int:id>', ventasView, name='venta_edit'),
    path('Venta/busca_produccion',ProduccionView.as_view(), name="busca_produccion"),
    path('Venta/borrar-detalle/<int:id>',borrar_detalle_factura, name="borrar_detalle"),
    path('Venta/ventas-masivas',ventas_masivasView, name="ventas_masivas"),
    
    path('Venta/imprimir/<int:id>',imprimir_venta_recibo, name="venta_imprimir"),
    path('Ventas/imprimir-todas/<str:f1>/<str:f2>',imprimir_venta_list, name="venta_imprimir_all"),

]

syshacienda/vent/models.py
from django.db import models
#Para los signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum

from baseapp.models import BaseFields
from mnt.models import Cliente, Cosecha, Produccion, Cultivo, Parametro

## Venta ******************************************** ##
# - Venta - #
class Venta(BaseFields):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True)
    fechaVenta = models.DateTimeField(auto_now_add=True)
    subTotal = models.FloatField(blank=True, null=True, default=0)
    totalVenta = models.FloatField(blank=True, null=True, default=0)
    porcIva    = models.IntegerField(blank=True, null=True, default=0)
    totalIva = models.FloatField(blank=True, null=True, default=0)

    def __str__(self):
        return '{}'.format(self.id)
   
    def save (self):
        self.totalVenta = float(self.totalVenta)
        self.porcIva = self.porcIva
        self.subTotal = float(self.subTotal)
        self.totalIva = float(self.totalIva)
        super(Venta,self).save() 

    class Meta:
        verbose_name_plural = "Ventas"
        db_table = 'venta'

# - DetalleVenta - #
class DetalleVenta(BaseFields):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE, null=True)
    cultivo = models.ForeignKey(Cultivo, on_delete=models.CASCADE, null=True)
    produccion = models.ForeignKey(Produccion, on_delete=models.CASCADE, null=True)
    cantidad = models.FloatField(blank=True, null=True)
    precio = models.FloatField(blank=True, null=True)  
    total = models.FloatField(blank=True, null=True, default=0)

    def __str__(self):
        return "{}".format(self.cultivo.nombre)

    def save (self):
        self.produccion = self.produccion
        self.cultivo = self.cultivo
        self.cantidad = self.cantidad
        self.precio = self.precio
        self.total = round(float(int(self.cantidad)) * float(self.precio),2)
        super(DetalleVenta, self).save()

    class Meta:
        verbose_name_plural = "DetalleVentas"
        db_table = 'detalle_venta'


@receiver(post_save, sender=DetalleVenta)
def detalle_fac_guardar(sender,instance,**kwargs):
    venta_id = instance.venta.id
    produccion_id = instance.produccion.id    
    venta = Venta.objects.get(pk=venta_id)
    iIva = venta.porcIva
    if venta:
        sub_total = DetalleVenta.objects \
            .filter(venta=venta_id) \
            .aggregate(total=Sum('total')) \
            .get('total',0.00)
        
        totaliva = round((sub_total * (iIva /100)),2)
        totalventa = round((sub_total + totaliva),2)
        venta.totalVenta = totalventa
        venta.subTotal  = round(sub_total,2)
        venta.totalIva = totaliva
        venta.porcIva = iIva
        venta.save()

    prod=Produccion.objects.filter(pk=produccion_id).first()
    if prod:
        cantidad = float(prod.cantidadVentaCosecha) + float(instance.cantidad)
        prod.cantidadVentaCosecha = round(cantidad,2)
        prod.save()

syshacienda/vent/forms.py
from cProfile import label
from dataclasses import fields
from datetime import date
#from socket import fromshare
from tkinter import Widget
from django import forms
from django.forms import DateInput

from mnt.models import Cliente, Cultivo, Produccion
from vent.models import Venta, DetalleVenta


class VentaForm(forms.ModelForm):
    cliente = forms.ModelChoiceField(
                queryset=Cliente.objects.filter(estado=True)
                    .order_by('identificacion'))
    cultivo = forms.ModelChoiceField(
                queryset=Cultivo.objects.filter(estado=True)
                    .order_by('nombre'))
    produccion = forms.ModelChoiceField(
                queryset=Produccion.objects.filter(estado=True)
                    .order_by('cultivo'))
    class Meta:
        model = Venta
        fields = ['cliente',
                    'totalVenta',                   
                    'estado']
        labels = {'totalVenta':'Total Venta',
                'estado': 'Estado'}

        Widget = {'totalVenta': forms.FloatField,
                'estado': forms.CheckboxInput} 

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        self.fields['cultivo'].empty_label =  "Seleccione el cultivo"
        self.fields['produccion'].empty_label =  "Seleccione la producción"
        self.fields['cliente'].empty_label =  "Seleccione el cliente"

class DetalleVentaForm:
    cliente = forms.ModelChoiceField(
                queryset=Cliente.objects.filter(estado=True)
                    .order_by('identificacion'))
    cultivo = forms.ModelChoiceField(
                queryset=Cultivo.objects.filter(estado=True)
                    .order_by('nombre'))
    produccion = forms.ModelChoiceField(
                queryset=Produccion.objects.filter(estado=True)
                    .order_by('cultivo'))
    class Meta:
        model = DetalleVenta
        fields = ['cultivo',
                    'produccion',
                    'cantidad',
                    'precio',
                    'estado']
        labels = {'cantidad':'Ingres cantidad',
                'precio': 'Precio venta',
                'estado': 'Estado'}

        Widget = {'cantidad': forms.FloatField,
                'precio': forms.FloatField,
                'estado': forms.CheckboxInput} 

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        self.fields['cultivo'].empty_label =  "Seleccione el cultivo"
        self.fields['produccion'].empty_label =  "Seleccione la producción"
        self.fields['cliente'].empty_label =  "Seleccione el cliente"

syshacienda/vent/templates/vent/borrar_detalle.html
<label class="text-danger">¿Anular Producto <b>{{ det.cultivo.nombre }}</b> de factura <b>{{ det.venta.id }}</b>?</label>
<div>
    <div class="form-group">
        <label class="control-label">Usuario</label>
        <input type="text" id="usuario" class="form-control" required>
    </div>
    <div class="form-group">
        <label class="control-label">Contraseña</label>
        <input type="password" id="password" class="form-control" required>
    </div>
</div>

syshacienda/vent/templates/vent/busca_produccion.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="col-xl-12 col-md-12 mb-12">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Buscar Producto Cosechado
                        </div>
                        <div class="dropdown-divider"></div>
                        
                        <div class="row">
                                <table
                                id="tblProduccion"
                                data-pagination="true"
                                data-search="true"
                                data-show-columns="true"
                                data-show-fullscreen="true"
                                data-locale="es-NI"
                                >
                                <thead>
                                  <th data-sortable="true" data-field="id">Id</th>        
                                  <th data-sortable="true" data-field="cultivo">Cultivo</th>
                                  <th data-sortable="true" data-field="insumo">Insumo</th>
                                  <th data-field="cantidadCosecha">Cant. Cosechada</th>
                                  <th data-field="cantidadVentaCosecha">Cant. Vendida</th>
                                  <th data-field="cantidadDisponible">Cant. Disponible</th>
                                  <th data-field="precio">Precio</th>
                                  <th class="all">Acciones</th>
                                </thead>
                                <tbody>
                                  {% for item in obj%}
                                  <tr>
                                    <td>{{ item.id }}</td>
                                    <td>{{ item.cultivo }}</td>
                                    <td>{{ item.insumo }}</td>
                                    <td>{{item.cantidadCosecha}}</td>
                                    <td>{{item.cantidadVentaCosecha}}</td>
                                    <td>{{item.cantidadCosecha - item.cantidadVentaCosecha }}</td>
                                    <td>{{item.precio}}</td>
                                    <td>
                                        {% if {{item.cantidadCosecha - item.cantidadVentaCosecha }} > 0 and item.estado %}
                                        <button class="btn btn-warning btn-circle" id="btnSelect" 
                                        onclick="seleccionarProducto({{item.id}},'{{item.cultivo.nombre}}',{{item.precio}})">
                                            <i class="far fa-hand-pointer"></i>
                                        </button>
                                        {% endif %}
                                    </td>
                                  </tr>
                                  {% endfor %}
                                </tbody>
                              </table>
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <!-- <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button> -->
                                <button type="button" id="btnCancelar" class="btn btn-success">
                                        <!-- onclick="return cerrar_modal()" -->
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 
{% block js_page %}
<script>
    $(function () {

        $("#btnCancelar").click(function(e){
            e.preventDefault();
            cerrar_modal();

        });
    });
    $('#tblProduccion').bootstrapTable();

    function seleccionarProducto(id,codigo,descripcion,precio){
        $("#id_produccion").val(codigo);
        $("#id_cultivo").val(descripcion);
        $("#id_precio").val(precio);
        $("#btnCancelar").click();
        $("#id_produccion").select();
        $("#id_produccion").focus();

    }

</script>
{% endblock %}

syshacienda/vent/templates/vent/venta_list.html
{% extends 'base/home.html' %}
{% load static %}

{% block csstables %}
  <!-- Custom fonts for this template -->
  <link href="{% static 'assets/vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" 
          rel="stylesheet">
  <!-- Custom styles for this template --> 
  <link href="{% static 'assets/vendor/css/sb-admin-2.min.css'%}" rel="stylesheet">
   <!-- Custom styles for this page -->
   <link href="{% static 'assets/vendor/datatables/dataTables.bootstrap4.min.css'%}" rel="stylesheet">
     <!-- jQuery Confirm -->
  <link rel="stylesheet" href="{% static 'assets/vendor/jquery_confirm/jquery-confirm.min.css' %}">
  <!-- XDSoft DateTimePicker  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" 
            integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />   
  <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/css/select2.min.css" rel="stylesheet" /> 
{% endblock csstables %}

{% block page_content %}  

<div class="container-fluid">
      
    <div class="app-card-body p-1 p-lg-1">
    </div>

<!-- Begin Page Content -->
        <div class="container-fluid">
          <!-- DataTales Example -->         
          <div class="card shadow mb-4" ><br/>
                <div class="app-card-body p-1 p-lg-1">
                    <div class="row gx-5 gy-3">
                      <div class="col-12 col-lg-3">
                            <h2 class="m-0 font-weight-bold text-primary text-center">Registro de ventas</h2>
                      </div>
                      <div class="col-md-3">
                        <a class="btn btn-primary" href="{% url 'vent:venta_new' %}"><i cass="far fa-calendar-plus"></i>Nueva Venta</a>
                      </div>
                      <div class="col-md-3">
                        <a class="btn btn-info" href="{% url 'mnt:cliente_new' %}"><i cass="far fa-calendar-plus"></i>Nuevo Cliente</a>
                      </div>
                      <div class="col-md-3">
                        <a class="btn btn-info" href="{% url 'mnt:produccion_new' %}"><i cass="far fa-calendar-plus"></i>Nueva Producción </a>
                      </div> 
                </div> <br/>
                {% if not obj %}
                    <div class="card-header py-2">
                      <h2 class="alert alert-info">No existe información</h2>
                    </div>
                {% else %}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-1"> Fecha Inicio</div>
                            <div class="col-md-2">
                              <input type="text" 
                                    class="form-class" 
                                    name="f1" 
                                    id="f1" 
                                    size="10"
                                    readonly>
                            </div>
                            <div class="col-lg-1"> Fecha Fin</div>
                            <div class="col-md-2">
                              <input type="text" 
                                    class="form-class" 
                                    name="f2" 
                                    id="f2" 
                                    size="10"
                                    readonly>
                            </div>

                            <div class="col-md-2">
                              <button class="btn btn-warning" type="button" id="btnPrint">Imprimir</button>
                            </div>
                        </div>
                        <table id="dataTable"
                              data-toggle="table"
                              data-pagination="true"
                              data-search="true"
                              data-show-columns="true"
                              data-show-toggle="true"
                              data-show-fullscreen="true"
                              data-locale="es-NI">
                          <thead>
                                {% block header_list %}
                                <tr>
                                    <th>No.</th>
                                    <th>Cliente</th>
                                    <th>Fecha Venta</th>
                                    <th>Sub-Total</th>
                                    <th>Total Iva</th>
                                    <th>Total Venta</th>
                                    <th class="all">Acciones</th>
                                </tr>
                                {% endblock %}
                          </thead>
                          <tfoot>
                                {% block footer_list %}
                                  <!--<tr>
                                    <th>No.</th>
                                    <th>Cliente</th>
                                    <th>Fecha Venta</th>
                                    <th>Sub-Total</th>
                                    <th>Total Iva</th>
                                    <th>Total Venta</th>
                                    <th class="all">Acciones</th>
                                  </tr>-->
                                {% endblock %}
                          </tfoot>
                          <tbody>
                                {% block body_list %}
                                    {% for item in obj %}
                                    <tr>
                                          <td>{{ item.id }}</td>
                                          <td>{{ item.cliente }}</td>
                                          <td>{{ item.fechaVenta | date:"d/m/Y" }}</td>
                                          <td>{{ item.subTotal }}</td>
                                          <td>{{ item.totalIva }}</td>
                                          <td>{{ item.totalVenta }}</td>
                                          <td>
                                            <a href="{% url 'vent:venta_edit' item.id %}" class="href btn btn-warning btn-circle">
                                                <i class="far fa-edit"></i>
                                            </a>
                                          </td>
                                    </tr>
                                    {% endfor %}
                                {% endblock %}
                          </tbody>
                        </table>
                    </div>
                  </div>
                {% endif %}
        </div>
        <!-- /.container-fluid -->
{% endblock page_content %}


{% block js_tablas %}
	<!-- Core plugin JavaScript-->
	<script src="{% static 'assets/vendor/jquery-easing/jquery.easing.min.js'%}"></script>
    <script src="{% static 'assets/vendor/js/jquery.chained.min.js'%}"></script>

	<!-- Page level custom scripts -->
    <script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table-locale-all.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js"></script>
{% endblock js_tablas %}

<script>
  var jq = jQuery.noConflict(true);
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% block js_page %}
{% endblock %}