syshacienda/baseapp/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from baseapp.views import Home

urlpatterns = [
    #path('', Home.as_view(), name='home'),
    path('', Home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='baseapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='baseapp/login.html'), name='logout'),
]

syshacienda/bi/urls.py
from django.urls import path, include
from bi.views import analiticaView, superficieView, rendimientoView, cantidadesView, \
                    costoproduccionView, precioventaView, lotescultivadosView, \
                    masproducidosView, valorminimoView, valormaximoView, valorpromedioView, \
                    masproduciraView, proximafechaView

urlpatterns = [
    path('analitica', analiticaView, name="analiticaView"),
    path('superficie', superficieView, name="superficieView"),
    path('rendimiento', rendimientoView, name="rendimientoView"),
    path('cantidades', cantidadesView, name="cantidadesView"),
    path('costoproduccion', costoproduccionView, name="costoproduccionView"),    
    path('precioventa', precioventaView, name="precioventaView"),    
    path('lotescultivados', lotescultivadosView, name="lotescultivadosView"),    
    path('masproducidos', masproducidosView, name="masproducidosView"),    
    path('valorminimo', valorminimoView, name="valorminimoView"),
    path('valormaximo', valormaximoView, name="valormaximoView"),
    path('valorpromedio', valorpromedioView, name="valorpromedioView"),
    path('masproducira', masproduciraView, name="masproduciraView"),
    path('proximafecha', proximafechaView, name="proximafechaView"),
]

syshacienda/syshacienda/urls.py
from django.contrib import admin
from django.urls import path, include
from baseapp import urls
from mnt import urls
from vent import urls
from api import urls
from bi import urls

urlpatterns = [
    path('', include(('baseapp.urls','baseapp'), namespace="baseapp")),
    path('mnt/', include(('mnt.urls','mnt'), namespace="mnt")),
    path('vent/', include(('vent.urls','vent'), namespace="vent")),
    path('api/', include(('api.urls','api'), namespace="api")),
    path('rpts/', include(('rpts.urls','rpts'), namespace="rpts")),
    path('bi/', include(('bi.urls','bi'), namespace="bi")),

    path('admin',admin.site.urls),

]

admin.site.site_header = 'Panel de control de Administración de Hacienda'
admin.site.index_title = 'ADMINISTRACIÓN DEL SISTEMA'
#admin.site.site_title = 'SysAdmin'
 # 

syshacienda/baseapp/models.py
from django.db import models
from django.contrib.auth.models import User

class BaseFields(models.Model):
    estado = models.BooleanField(default=True, verbose_name="Estado del registro")
    fechaCreacion = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creacion")
    fechaModificacion = models.DateTimeField(auto_now = True, verbose_name="Fecha de actualizacion", blank=True, null=True)
    usuarioCreacion = models.ForeignKey(User, on_delete = models.DO_NOTHING, verbose_name="Usuario registra")
    usuarioModificacion = models.IntegerField(blank=True, null=True, verbose_name = "Usuario modifica")

    class Meta:
        abstract = True

class ContactFields(models.Model):
    telefono = models.CharField(max_length=20, blank=True, null=True, verbose_name = "Telefono de contacto")
    celular = models.CharField(max_length=10, blank=True, null=True, verbose_name = "Número celular")
    email = models.CharField(max_length=50, blank=True, null=True, verbose_name = "Correo electrónico")
    direccion = models.CharField(max_length=100, verbose_name="Direccion")
    ciudad = models.CharField(max_length=20, blank=True, null=True, verbose_name= "Ciudad")

    class Meta:
        abstract = True

class PersonFields(models.Model):
    nombre = models.CharField(max_length=25, verbose_name="Nombre")
    apellido = models.CharField(max_length=25, verbose_name="Apellido",blank=True, null=True,)
    identificacion = models.CharField(max_length=15, unique=True, verbose_name = "Número de identificación")
    
    class Meta:
        abstract = True

syshacienda/baseapp/views.py
from django.db import models
from django.shortcuts import render,redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Sum, F, DateTimeField, Count, FloatField, IntegerField, Prefetch, Case, When
from datetime import datetime, timezone, timedelta, date
from django.db.models.functions import TruncMonth, TruncYear, ExtractMinute, ExtractMonth, ExtractYear, Cast, Coalesce, TruncDay
from django.utils.dateparse import parse_date
import json
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import authenticate

import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression 


from mnt.views import ClienteView, CultivoView, ProduccionView, \
                            HaciendaView, EmpleadoNew, AsignacionView, \
                            ProveedorNew, RegistroInsumoNew
from mnt.models import Cliente, Cultivo, Produccion, DescripcionLote, \
                        Hacienda, Empleado, Asignacion, \
                        Proveedor, RegistroInsumo, Insumo, \
                        Parametro
from vent.views import ventasView, VentaView
from vent.models import Venta, DetalleVenta

#class Home(LoginRequiredMixin, generic.ListView):
#    template_name = 'baseapp/home.html'
#    login_url = "/login"

@login_required(login_url='/login/')
def Home(request):
    template_name='baseapp/home.html'
    anioactual = datetime.now().year
    anioanterior = anioactual-1
    tiempobi = int(Parametro.objects.filter(nombreParametro="TIEMPOBI") \
                                .values_list('valorParametro', flat=True) \
                                .annotate(valor_parametro=Cast('valorParametro', IntegerField())) \
                                .get())
    if tiempobi is None or not tiempobi:
        tiempobi = 180
    
    tventasanio = Venta.objects.filter(fechaVenta__year=anioactual)\
                                .aggregate(sum_total=Cast(Sum('totalVenta'),IntegerField()))
    if tventasanio['sum_total'] is None:
        tventasanio = 0
    else:
        tventasanio = tventasanio['sum_total']

    tventasanioanterior = Venta.objects.filter(fechaVenta__year=anioanterior)\
                                .aggregate(sum_total=Cast(Sum('totalVenta'),IntegerField()))
    if tventasanioanterior['sum_total'] is None:
        tventasanioanterior = 0
    else:
        tventasanioanterior = tventasanioanterior['sum_total']

    
    prod = Produccion.objects.filter(fecha__year=anioactual) \
                            .aggregate(sum_Cosecha=Cast(Sum('cantidadCosecha'),IntegerField()))

    vent = Produccion.objects.filter(fecha__year=anioactual) \
                            .aggregate(sum_Venta=Cast(Sum('cantidadVentaCosecha'),IntegerField()))

    if prod['sum_Cosecha'] is None:
        sumCosecha = 0
    else:
        sumCosecha = prod['sum_Cosecha']

    if vent['sum_Venta'] is None:
        sumVentas = 0
    else:
        sumVentas = vent['sum_Venta']

    
    tcompras = RegistroInsumo.objects.filter(fechaCompra__year=anioactual) \
                                    .aggregate(sum_precio=Cast(Sum('precio'),IntegerField()))

    if tcompras['sum_precio'] is None:
        tcompras = 0
    else:
        tcompras = tcompras['sum_precio']

    tcompras_ant = RegistroInsumo.objects.filter(fechaCompra__year=anioanterior) \
                                    .aggregate(sum_precio=Cast(Sum('precio'),IntegerField()))

    if tcompras_ant['sum_precio'] is None:
        tcompras_ant = 0
    else:
        tcompras_ant = tcompras_ant['sum_precio']

    ventas = Venta.objects.filter(fechaVenta__year=anioactual,)
    topventas =  ventas.values('fechaVenta__year', 'detalleventa__cultivo__nombre') \
                .annotate(det_cantidad=Cast(Sum('detalleventa__cantidad'), IntegerField()))\
                .exclude(det_cantidad=None) \
                .order_by('-det_cantidad')[:10]

    #obtener fecha actual en formato: YYYY-MM-DD
    fecha_actual = datetime.now()
    fecha_inicio = fecha_actual - timedelta(days=7)

    #crear objeto con rango de días entre fecha_actual y fecha_inicio, formato: YYYY-MM-DD
    #semana = [pd.date_range(start=fecha_inicio, end=fecha_actual, freq='D').strftime('%Y-%m-%d')]
    ventas_semana = []
    for i in range(8):
        fecha_venta = fecha_inicio + timedelta(days=i)
        fecha_venta = fecha_venta.strftime('%Y-%m-%d')
        ventas_semana.append({'fecha_venta': fecha_venta, 'total_venta': 0})
    #obtener ventas de la semana agrupadas por día
    #ventas_semana = Venta.objects.filter(fechaVenta__range=[fecha_inicio, fecha_actual]) \
    #                            .annotate(total_venta=Sum('totalVenta'), fecha_venta=TruncDay('fechaVenta')) \
    #                            .order_by('fechaVenta')[:8]
                                
    dato_ventas = Venta.objects.filter(fechaVenta__gte=(fecha_inicio- timedelta(days=1)) ) \
                                .annotate(fecha=Cast('fechaVenta', DateTimeField())) \
                                .values('fecha') \
                                .annotate(total=Cast(Sum('totalVenta'), IntegerField())) \
                                .order_by('fecha')
    
    if not dato_ventas:
        dato_ventas = ventas_semana
    else: #cruzar la información entre la variable semana y ventas_semana, y actualizar el total_ventas por día.
        for dato_venta in dato_ventas:
            a = dato_venta['fecha'].strftime('%Y-%m-%d')
            for venta_semana in ventas_semana:
                if venta_semana['fecha_venta'] == dato_venta['fecha'].strftime('%Y-%m-%d'):
                    venta_semana['total_venta'] = venta_semana['total_venta'] + dato_venta['total']
                    break

        
        
    ventas = Venta.objects.filter(fechaVenta__gte=datetime.now() - timedelta(days=(tiempobi+8))).values('fechaVenta', 'totalVenta')
    if ventas:
        #realizamos la proyección basado en el parametro tiempobi: 180 días
        df = pd.DataFrame(ventas)
        df['fechaVenta'] = pd.to_datetime(df['fechaVenta']) # Convertimos la columna fechaVenta a tipo datetime
        df['dias'] = (df['fechaVenta'] - df['fechaVenta'].min())  / np.timedelta64(1,'D') # Creamos una columna con el número de días desde el primer registro de venta 
        X = df[['dias']] # Definimos X como la columna dias del DataFrame 
        y = df[['totalVenta']] # Definimos y como la columna totalVenta del DataFrame 
        model = LinearRegression() # Creamos un modelo de regresión lineal 
        model.fit(X, y) # Entrenamos el modelo con los datos obtenidos 
        predicciones = model.predict([[181], [182], [183], [184], [185], [186], [187], [188]]) # Realizamos predicciones para los siguientes 8 días 
        pred_formateada = np.round(predicciones, decimals=0).tolist() # Redondeamos las predicciones a 0 decimales 
        pred_formateada =  [int(numero[0]) for numero in pred_formateada] # formateamos la lsta
         

        context = {'anioactual': anioactual, 'anioanterior': anioanterior,
        'tventasanio': tventasanio, 'tventasanioanterior': tventasanioanterior,
        'sumCosecha': sumCosecha, 'sumVentas': sumVentas, 'tcompras': tcompras,
        'tcompras_ant': tcompras_ant, 'topventas': topventas, 'ventas_semana': ventas_semana,
        'predicciones_df': pred_formateada
        }
    else:
        context = {'anioactual': anioactual, 'anioanterior': anioanterior,
        'tventasanio': tventasanio, 'tventasanioanterior': tventasanioanterior,
        'sumCosecha': sumCosecha, 'sumVentas': sumVentas, 'tcompras': tcompras,
        'tcompras_ant': tcompras_ant, 'topventas': topventas, 'ventas_semana': ventas_semana,
        'predicciones_df': None
        }
        
    return render(request,
                    template_name,
                    context)

syshacienda/baseapp/templates/baseapp/accesonegado.html
{% extends 'baseapp/home.html' %}
{% block page_content %}
    <div class="col-xl-6 col-md-6 mb-6">
        <div class="card border-left-danger shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
            <div class="col mr-2">
                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                    Usuario: <mark>{{ user.username }}  {{user.get_full_name }}</mark> 
                </div>
                <div class="dropdown-divider"></div>

                <div class="row">
                    <mark>No tiene suficientes privilegios</mark> para cargar opción solicitada.
                    <br>
                    <small>Para poder acceder, debes loguearte con un usuario con privilegios necesarios.</small>

                </div>
                <div class="dropdown-divider"></div>
                <div class="row">
                    <div class="col">
                        <a href="{% url 'baseapp:home' %}" class="btn btn-success"><span class="fa fa-home"></span> Ir a Inicio</a>
                        <a href="{% url 'baseapp:login' %}" class="btn btn-success"><span class="fa fa-user"></span> Ingresar con otro Usuario</a>
                    </div>
                </div>
            </div>
            <div class="col-auto">
                <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
            </div>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

syshacienda/baseapp/templates/baseapp/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>SISTEMA DE ADMINISTRACION DE HACIENDAS</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="SISTEMA DE ADMINISTRACION DE HACIENDAS">
    <meta name="author" content="">    
    
    <!-- FontAwesome JS-->
    <script defer src="{% static 'assets/plugins/fontawesome/js/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/portal.css' %}">

</head> 

<body class="app app-login p-0">    	
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="#">
						<img class="logo-icon me-2 " width: "100px" height: "100px" src="{% static 'assets/images/logohacienda.png' %}" alt="logo"></a></div>
					<h2 class="auth-heading text-center mb-5">Inicie Sesión</h2>
					<small class="text-danger">
						{% if form.errors %}
							{% for field in form %}
								{% if field.errors %}
									{% for error in field.errors %}
										{{error | escape}}
									{% endfor %}
								{% endif%}
							{% endfor %}

							{% if form.non_field_errors %}
								{% for error in form.non_field_errors %}
									{{error | escape}}
								{% endfor %}
							{% endif %}
						{% endif %}
					</small>
			        <div class="auth-form-container text-start">
						<form class="auth-form login-form" method = "POST">         
							{% csrf_token %}
							<div class="email mb-3">
								<label class="sr-only" for="signin-email">Usuario</label>
								<input id="id_username" name="username" 
										type="text" class="form-control signin-email" 
										placeholder="Usuario" required="required"
										>
							</div><!--//form-group-->
							<div class="password mb-3">
								<label class="sr-only" for="signin-password">Password</label>
								<input id="id_password" name="password" 
										type="password" class="form-control signin-password" 
										placeholder="Password" required="required"
										>

							</div><!--//form-group-->
							{# { form.as_p } #}
							<div class="text-center">
								<button type="submit" class="btn app-btn-primary w-100 theme-btn mx-auto"  >Iniciar Sesión</button>
							</div>
						</form>
						
						<div class="auth-option text-center pt-5">Si no tiene una cuenta, comunicarse con el administrador </div>
					</div><!--//auth-form-container-->	

			    </div><!--//auth-body-->
		    
			    <footer class="app-auth-footer">
				    <div class="container text-center py-3">				       
				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->
	    <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col">
		    <div class="auth-background-holder">
		    </div>
		    <div class="auth-background-mask"></div>
		    <div class="auth-background-overlay p-3 p-lg-5">
			    <div class="d-flex flex-column align-content-end h-100">
				    <div class="h-100"></div>
				</div>
		    </div><!--//auth-background-overlay-->
	    </div><!--//auth-background-col-->
    
    </div><!--//row-->


</body>
</html> 